#!/bin/bash
chmod u+x                                  |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
                                                                                                                     |
-=--:%%--F1 